# Generated by Django 3.2 on 2023-03-14 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('preset_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preset_adress', models.CharField(blank=True, max_length=100, null=True)),
                ('preset_post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('preset_city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
