# Generated by Django 3.2 on 2023-02-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20230209_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='plan',
        ),
    ]
