# Generated by Django 3.2 on 2023-03-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='include_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='include_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='include_3',
        ),
    ]
