# Generated by Django 3.2 on 2023-01-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_category_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pt_sessions',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Subscriptions and pt_sessions'},
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='include_1',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='include_2',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='include_3',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
